### ISSUE TITLE
TODO on split-db

### ISSUE THREAD

**Issue by Niols** [paris-branch/dancelor#12]
In GitLab by @VLanvin on May 31, 2019, 09:11

* [x]  Fix alignment issues between table headers and content
* [ ]  Add actions in set list
* [x]  Add download links in individual tunes, sets and programs
* [x]  Do not send tune contents to client (and close corresponding issue)
* [x]  Add save/clear buttons to set composer
* [x]  Proper handling/display of errors (at least for the kind) when saving a set
* [x]  In composer, remove search bar text when a tune has been selected
* [x]  Beautiful icons in buttons
* [x]  Set save
* [x]  Fix cache problem when requesting different transpose targets (done on master?)
